# Thanks to Pathplanner and WPILib for showing what CI is and what it does

name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  # Unused for now ^,*
  VERSION_NAME: 0.0.0-dev-${{ github.run_number }}

jobs:

  # Maybe next time we can get clang-format checker
  #formatting:
  #  name: "Check Formatting"
  #  runs-on: ubuntu-24.04
  #  container: wpilib/ubuntu-base:24.04
  #
  #  steps:
  #    - name: Checkout repo
  #      uses: actions/checkout@v4
  #    
  #    - name: Grant execute permission for gradlew
  #      run: chmod +x gradlew
  #      # working-directory: .
  #    
  #    - name: Check formatting
  #      run: ./gradlew spotlessCheck -Ptoolchain-optional-roboRio
  #      # working-directory: .
  
  # We don't do any tests


  # We program on Windows, ensure that the program is portable for other pathforms
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2025-22.04
            artifact-name: Athena
            build-options: "-Ponlylinuxathena"
          - container: wpilib/ubuntu-base:24.04
            artifact-name: Linux
            build-options: "-Ponlylinuxx86-64"
          # CTRE Lib is not loading so don't do it
          # - container: wpilib/raspbian-cross-ubuntu:bookworm-22.04
          #  artifact-name: Arm32
          #  build-options: "-Ponlylinuxarm32"
          - container: wpilib/aarch64-cross-ubuntu:bookworm-22.04
            artifact-name: Arm64
            build-options: "-Ponlylinuxarm64"
    name: "Build - ${{ matrix.artifact-name }}"
    # needs: [formatting]
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # working-directory: .
      
      - name: Get RoboRio Toolchains
        run: ./gradlew installRoboRioToolchain

      - name: Build
        run: ./gradlew build ${{ matrix.build-options }} -x spotlessCppApply -x spotlessCppCheck -x spotlessCppDiagnose
        # working-directory: .

  # Make sure that simulation code can work on both Windows and MacOS
  build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 13.3
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: Win64
            os-name: windows
          - os: macos-15
            artifact-name: macOS
            os-name: macos
    name: "Build - ${{ matrix.artifact-name }}"
    # needs: [formatting]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      
      - name: Grant execute permission for gradlew (mac)
        if: ${{ matrix.os-name == 'macos' }}
        run: chmod +x gradlew
      
      - name: Get RoboRio Toolchains
        run: ./gradlew installRoboRioToolchain
        # working-directory: .

      - name: Build
        run: ./gradlew build -Pbuildalldesktop -x spotlessCppApply -x spotlessCppCheck -x spotlessCppDiagnose
        # working-directory: .
  